### ISSUE TITLE
Implement database with front end

### ISSUE THREAD

**Issue by obssuthk** [BryanBH/SWE_Final#42]
End to end implementation of the database.

**Comment by obssuthk** [comment]
Sign up and log in now functional with database
![loginworkingsnip](https://user-images.githubusercontent.com/90472692/163245712-9e146306-2043-4bc8-a693-c5d9c81f4b0d.PNG)
.

**Comment by JordanW1atWIT** [comment]
![Capture](https://user-images.githubusercontent.com/71137820/164094075-325ec9d4-c86d-4b6d-ba2b-b6b8bd785e92.PNG)

Image gives image url to display, phone number is the restaurant's phone number, rating is rating out of 5, name is the name, userID is the userID to tell who the bookmark belongs to. Webpage uses basic brute force algorithm to check if the userID matches the current user and see if it should display
